node1 ansible_host=192.168.56.11
node2 ansible_host=192.168.56.12
node3 ansible_host=192.168.56.13

[demo_nodes]
node1
node2
node3

[demo_nodes:vars]
ansible_user=ansible
ansible_ssh_private_key_file=./ansible_key
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[dd_full]
node1

[dd_min]
node2
node3
