---
# The Master Orchestrator
# "I am large, I contain multitudes." - Walt Whitman (and Ansible)

- import_playbook: maintenance.yml
- import_playbook: datadog.yml
- import_playbook: datadog-minimal.yml
- import_playbook: ping_collector.yml
- import_playbook: ping_dashboard.yml
- import_playbook: custom_check.yml
